[phases.setup]
nixPkgs = ['nodejs-18_x', 'pnpm']

[phases.install]
cmds = ['pnpm install --prefer-offline --prod=false']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'npx serve dist -s -p $PORT'
